### ISSUE TITLE
badly defined bounding box

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop#1]
**Used example code:**
[test_m2l3.zip](https://github.com/Loop3D/map2loop-3/files/11588709/test_m2l3.zip)

**Got this error:**
(map2loop-3) mark@DEP66241:~/map2loop-3$ python test_m2l3.py
Traceback (most recent call last):
  File "test_m2l3.py", line 15, in <module>
    proj = Project(use_australian_state_data="SA",
  File "<@beartype(map2loop.project.Project.__init__) at 0x7f494dd21790>", line 260, in __init__
  File "/home/mark/map2loop-3/map2loop/project.py", line 138, in __init__
    raise TypeError(f"Invalid type for bounding_box {type(bounding_box)}")
TypeError: Invalid type for bounding_box <class 'NoneType'>

**Comment by RoyThomsonMonash** [comment]
This was a type in the README.  bbox should have been bounding_box. This has been fixed.
